/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_MyOpenVINO_WRAP_H_
#define SWIG_MyOpenVINO_WRAP_H_

class SwigDirector_CallbackHandlerBase : public CallbackHandlerBase, public Swig::Director {

public:
    SwigDirector_CallbackHandlerBase();
    virtual void InferCallBack(int inferID, std::string const &inputImageFile, bool isSuccessed, std::vector< float > const &results);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, char *, unsigned int, void *);
    void swig_connect_director(SWIG_Callback0_t callbackInferCallBack);

private:
    SWIG_Callback0_t swig_callbackInferCallBack;
    void swig_init_callbacks();
};


#endif
