//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class DeviceVector : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IEnumerable<Device>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DeviceVector(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DeviceVector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DeviceVector() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          MyOpenVINOPINVOKE.delete_DeviceVector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public DeviceVector(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Device element in c) {
      this.Add(element);
    }
  }

  public DeviceVector(global::System.Collections.Generic.IEnumerable<Device> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (Device element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public Device this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(Device[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(Device[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, Device[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public Device[] ToArray() {
    Device[] array = new Device[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<Device> global::System.Collections.Generic.IEnumerable<Device>.GetEnumerator() {
    return new DeviceVectorEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new DeviceVectorEnumerator(this);
  }

  public DeviceVectorEnumerator GetEnumerator() {
    return new DeviceVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class DeviceVectorEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<Device>
  {
    private DeviceVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public DeviceVectorEnumerator(DeviceVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public Device Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (Device)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    MyOpenVINOPINVOKE.DeviceVector_Clear(swigCPtr);
  }

  public void Add(Device x) {
    MyOpenVINOPINVOKE.DeviceVector_Add(swigCPtr, (int)x);
  }

  private uint size() {
    uint ret = MyOpenVINOPINVOKE.DeviceVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = MyOpenVINOPINVOKE.DeviceVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    MyOpenVINOPINVOKE.DeviceVector_reserve(swigCPtr, n);
  }

  public DeviceVector() : this(MyOpenVINOPINVOKE.new_DeviceVector__SWIG_0(), true) {
  }

  public DeviceVector(DeviceVector other) : this(MyOpenVINOPINVOKE.new_DeviceVector__SWIG_1(DeviceVector.getCPtr(other)), true) {
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

  public DeviceVector(int capacity) : this(MyOpenVINOPINVOKE.new_DeviceVector__SWIG_2(capacity), true) {
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

  private Device getitemcopy(int index) {
    Device ret = (Device)MyOpenVINOPINVOKE.DeviceVector_getitemcopy(swigCPtr, index);
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private Device getitem(int index) {
    Device ret = (Device)MyOpenVINOPINVOKE.DeviceVector_getitem(swigCPtr, index);
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, Device val) {
    MyOpenVINOPINVOKE.DeviceVector_setitem(swigCPtr, index, (int)val);
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(DeviceVector values) {
    MyOpenVINOPINVOKE.DeviceVector_AddRange(swigCPtr, DeviceVector.getCPtr(values));
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

  public DeviceVector GetRange(int index, int count) {
    global::System.IntPtr cPtr = MyOpenVINOPINVOKE.DeviceVector_GetRange(swigCPtr, index, count);
    DeviceVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeviceVector(cPtr, true);
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, Device x) {
    MyOpenVINOPINVOKE.DeviceVector_Insert(swigCPtr, index, (int)x);
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, DeviceVector values) {
    MyOpenVINOPINVOKE.DeviceVector_InsertRange(swigCPtr, index, DeviceVector.getCPtr(values));
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    MyOpenVINOPINVOKE.DeviceVector_RemoveAt(swigCPtr, index);
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    MyOpenVINOPINVOKE.DeviceVector_RemoveRange(swigCPtr, index, count);
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

  public static DeviceVector Repeat(Device value, int count) {
    global::System.IntPtr cPtr = MyOpenVINOPINVOKE.DeviceVector_Repeat((int)value, count);
    DeviceVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new DeviceVector(cPtr, true);
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    MyOpenVINOPINVOKE.DeviceVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    MyOpenVINOPINVOKE.DeviceVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, DeviceVector values) {
    MyOpenVINOPINVOKE.DeviceVector_SetRange(swigCPtr, index, DeviceVector.getCPtr(values));
    if (MyOpenVINOPINVOKE.SWIGPendingException.Pending) throw MyOpenVINOPINVOKE.SWIGPendingException.Retrieve();
  }

}
