//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MyOpenVINO {
  public static IMyOpenVINO GetInstance() {
    global::System.IntPtr cPtr = MyOpenVINOPINVOKE.GetInstance();
    IMyOpenVINO ret = (cPtr == global::System.IntPtr.Zero) ? null : new IMyOpenVINO(cPtr, false);
    return ret;
  }

}
